apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: demo
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 32500
    protocol: TCP
  selector:
    run: my-nginx
